spring.application.name=SophiaBackend
# Configuration de la base de donnees PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/sophia_bdd
spring.datasource.username=postgres
spring.datasource.password=D@tabase#07
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
